// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SousMalins.Data;

#nullable disable

namespace SousMalins.Migrations
{
    [DbContext(typeof(SousMalinsDbContext))]
    [Migration("20260501100937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("SousMalins.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SousMalins.Models.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Plafond")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoldeInitial")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SoldeInitialDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Comptes");
                });

            modelBuilder.Entity("SousMalins.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .HasColumnType("TEXT");

                    b.Property<int>("Montant")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransfertId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeTransaction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("CompteId");

                    b.HasIndex("TransfertId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SousMalins.Models.Transfert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompteDestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompteSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .HasColumnType("TEXT");

                    b.Property<int>("Montant")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompteDestinationId");

                    b.HasIndex("CompteSourceId");

                    b.ToTable("Transferts");
                });

            modelBuilder.Entity("SousMalins.Models.Transaction", b =>
                {
                    b.HasOne("SousMalins.Models.Categorie", "Categorie")
                        .WithMany("Transactions")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SousMalins.Models.Compte", "Compte")
                        .WithMany("Transactions")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousMalins.Models.Transfert", "Transfert")
                        .WithMany("Transactions")
                        .HasForeignKey("TransfertId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Categorie");

                    b.Navigation("Compte");

                    b.Navigation("Transfert");
                });

            modelBuilder.Entity("SousMalins.Models.Transfert", b =>
                {
                    b.HasOne("SousMalins.Models.Compte", "CompteDestination")
                        .WithMany("TransfertsDestination")
                        .HasForeignKey("CompteDestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousMalins.Models.Compte", "CompteSource")
                        .WithMany("TransfertsSource")
                        .HasForeignKey("CompteSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteDestination");

                    b.Navigation("CompteSource");
                });

            modelBuilder.Entity("SousMalins.Models.Categorie", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SousMalins.Models.Compte", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("TransfertsDestination");

                    b.Navigation("TransfertsSource");
                });

            modelBuilder.Entity("SousMalins.Models.Transfert", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
